### PR TITLE
Fixes obs browser source issues

### LINKED ISSUE #7: Connection refused
image
I did everything right I took the first key and put it in and did centralus and tried launching it but it didn't work. Sadge

### PR DESCRIPTION
**Pull request by daronyondem**
Resolves the issues described in #7

### CODE REVIEW

File: js/subtitles.js [hunk 1]
```diff
@@ -117,7 +117,16 @@
             subtitles.innerHTML = 'Unable to connect due to network issue or unable to gain microphone access.';
         }, 15000);
 
-        recognizer.startContinuousRecognitionAsync();
+        var userAgent = navigator.userAgent.toLowerCase();
+        if (userAgent.indexOf(' electron/') > -1) {
```
Comment (daronyondem) [inline js/subtitles.js:121]: The idea here is not to break the current functionality when the page is hosted in Electron. The user interaction requirement is only enforced when hosted in the browser sandbox.
